[build]
  base = ""
  publish = "build"
  command = "npm run build"
  environment = { NODE_VERSION = "16" }

[dev]
  publish = "static"

[[headers]]
  for = "/jim-navbar.js"
    [headers.values]
    Access-Control-Allow-Origin = "*"